GROUP_NAME=io.github.ppzxc
ARTIFACT_NAME=sandbox
VERSION_NAME=0.0.1
VERSION_CODE=1

POM_NAME=sandbox
POM_DESCRIPTION=Utility To My Taste
POM_INCEPTION_YEAR=2024
POM_URL=https://github.com/ppzxc/sandbox

POM_LICENSE_NAME=The Apache Software License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo

POM_DEVELOPER_ID=ppzxc
POM_DEVELOPER_NAME=JeongHa Cho
POM_DEVELOPER_EMAIL=cjh8487@naver.com
POM_DEVELOPER_URL=https://github.com/ppzxc/

POM_SCM_URL=https://github.com/ppzxc/sandbox
POM_SCM_CONNECTION=scm:git:git://github.com/ppzxc/sandbox.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/ppzxc/sandbox.git

POM_ISSUE_MANAGEMENT_URL=https://github.com/ppzxc/sandbox/issues
